version: 0.2

phases:
    install:
      commands:
        - echo Entered the install phase...
        - apt-get update -y
        - apt-get install -y cake
    build:
      commands:
        - cd $CODEBUILD_SRC_DIR
        - pwd
        - cake

