version: 0.2

phases:
    install: 
      commands:
        - dotnet tool install --framework netcoreapp2.1  --global Cake.Tool --version 0.32.0
        - export PATH="$PATH:/root/.dotnet/tools"
    build:
      commands:
        - dotnet --list-sdks
        - dotnet --version
        - ls
        - dotnet-cake
        - ls ./artifacts


