version: 0.2

phases:
    install: 
      commands:
        - apt-get update
        - apt-get install apt-transport-https
        - wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
        - dpkg -i packages-microsoft-prod.deb
        - apt-get update
        - apt-get -y upgrade mono 
        - apt-get install -y dotnet-sdk-2.1 
        - chmod +x build.sh
    build:
      commands:
        - dotnet --list-sdks
        - dotnet --version
        - ls
        - ./build.sh


