version: 0.2

phases:
    install:
      commands:
        - echo Entered the install phase...
        - add-apt-repository universe -y
        - apt-get update -y
        - apt-get install apt-transport-https -y
        - apt-get update -y
        - apt-get install dotnet-sdk-2.1.5
    build:
      commands:
        - dotnet --list-sdks
        - dotnet --version
        - cd $CODEBUILD_SRC_DIR
        - ls
        - chmod +x build.sh
        - ./build.sh


