version: 0.2

phases:
    install: 
      commands:
        - chmod +x build.sh
    build:
      commands:
        - mono
        - dotnet --list-sdks
        - dotnet --version
        - ls
        - ./build.sh


