version: 0.2

phases:
    install: 
      commands:
        - dotnet tool install --framework netcoreapp2.1  --global Cake.Tool --version 0.32.0
        - export PATH="$PATH:/root/.dotnet/tools"
    build:
      commands:
        - dotnet-cake
        - aws cloudformation help
        - aws cloudformation package --template-file template.yaml --s3-bucket test --output-template-file outputTemplate.yaml

artifacts:
    type: zip
    files:
      - template.yaml
      - outputTemplate.yaml


